// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmVKrXnVMReZ1qWWhP69XYDB_kBmulNyI',
    appId: '1:400589711865:web:9a15841e5759f065f47528',
    messagingSenderId: '400589711865',
    projectId: 'flutter-project-d45de',
    authDomain: 'flutter-project-d45de.firebaseapp.com',
    storageBucket: 'flutter-project-d45de.firebasestorage.app',
    measurementId: 'G-QJRLTHJFTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBkjnHo4aQHWbJ_E_QMmwXJaxxlygkMQ',
    appId: '1:400589711865:android:f3e38aa424dd1d53f47528',
    messagingSenderId: '400589711865',
    projectId: 'flutter-project-d45de',
    storageBucket: 'flutter-project-d45de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-fHqPbijxuWsYKpG-aKGmLEKpXk_2SM',
    appId: '1:400589711865:ios:d6fd94cb2171e26ff47528',
    messagingSenderId: '400589711865',
    projectId: 'flutter-project-d45de',
    storageBucket: 'flutter-project-d45de.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-fHqPbijxuWsYKpG-aKGmLEKpXk_2SM',
    appId: '1:400589711865:ios:d6fd94cb2171e26ff47528',
    messagingSenderId: '400589711865',
    projectId: 'flutter-project-d45de',
    storageBucket: 'flutter-project-d45de.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmVKrXnVMReZ1qWWhP69XYDB_kBmulNyI',
    appId: '1:400589711865:web:41d3554b715d037df47528',
    messagingSenderId: '400589711865',
    projectId: 'flutter-project-d45de',
    authDomain: 'flutter-project-d45de.firebaseapp.com',
    storageBucket: 'flutter-project-d45de.firebasestorage.app',
    measurementId: 'G-BG7EY4X099',
  );
}
